CREATE TABLE IF NOT EXISTS records(
  id VARCHAR(767) PRIMARY KEY,
  parent VARCHAR(767) DEFAULT NULL,
  value LONGBLOB,
  INDEX (parent),
  FOREIGN KEY (parent) REFERENCES records(id) ON DELETE CASCADE
)
